### ISSUE TITLE
Update request: Changes

### ISSUE THREAD

**Issue by imbaimbaimba** [iammexx/home-assistant-config#13]
Hi,

I posted on your home assistant forum thread. However, I will also add it here:

First of all, I noticed that “Feels like” and “Today’s high” did not translate to Danish. I asked on the home assistant discord server, and got help figuring it out, including the next things I found.

I changed the fr case to:
case “da” :
return {
feelsLike: “Føles som”,
maxToday: “Højeste i dag”,

And it worked. Then I found that wind directions also did not translate, and were only written as acronyms, where I would prefer written out. So I changed it to:
const windDirections_da = [‘Nord’,‘Nord-Nordøst’,‘Nordøst’,‘Øst-Nordøst’,‘Øst’,‘Øst-Sydøst’,‘Sydøst’,‘Syd-Sydøst’,‘Syd’,‘Syd-Sydvest’,‘Sydvest’,‘Vest-Sydvest’,‘Vest’,‘Vest-Nordvest’,‘Nordvest’,‘Nord-Nordvest’,‘Nord’];

Then I noticed my wind speed was reporting km/h, where it should report km/t (hours = timer in danish). But adding it this, it was also giving me the m/s value and putting km/h unit on it. Lastly, I think the way of reporting the wind speed and direction was unnatural, so I changed it to report like “speed” from “direction”. I found out that changing the wind variable could do it:
var wind = this.config.entity_wind_speed && this.config.entity_wind_bearing ? html<li><span class="ha-icon"><ha-icon icon="mdi:weather-windy"></ha-icon></span><span id="beaufort-text">${this.current.beaufort}</span><span id="wind-speed-text">${this.current.windSpeed}</span><span class="unit"> m/s</span><span id="wind-bearing-text"> fra ${this.current.windBearing}</span></li> : ``;

Can you maybe include these things? :)

**Comment by iammexx** [comment]
See response in forum....
