### ISSUE TITLE
0.88.0b3 breaks Get LitElement from an existing component

### ISSUE THREAD

**Issue by DavidFW1960** [iammexx/home-assistant-config#14]
see https://github.com/thomasloven/lovelace-card-tools/pull/11/commits/1cf927adcac12f1254c87eb8c54bde29f5eac8be

I tried to create a PR but couldn't

Change line 4 to:
```
var LitElement = LitElement || Object.getPrototypeOf(customElements.get("home-assistant-main"));
```

**Comment by iammexx** [comment]
This is complete.  Use v 0.10.2 or later.
