### ISSUE TITLE
Home Assistant V0.91.0 has just changed sensor name 

### ISSUE THREAD

**Issue by yvessa** [iammexx/home-assistant-config#19]
Since Home Assistant V0.91.0 has just changed some sensors name, card configuration has to be changed for every sensor ending with a numerical value.  

ie.
entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
renamed to
entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d

**Comment by iammexx** [comment]
README updated to reflect change
