### ISSUE TITLE
tracker.json

### ISSUE THREAD

**Issue by AcidSleeper** [iammexx/home-assistant-config#2]
Hello

Could you make a tracker.json file so that we thru "custom updater" can update automaticly when new version is made!?

Thanks in advance!

**Comment by iammexx** [comment]
I don't use that component but if someone can provide details I can certainly add the file.

**Comment by AcidSleeper** [comment]
Look at [https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json](url) and change the relevant information to fit your information.

Looks like this for mini-graph-card

```
{
    "mini-graph-card-bundle": {
      "updated_at": "2018-12-22",
      "version": "0.1.0",
      "remote_location": "https://github.com/kalkih/mini-graph-card/releases/download/v0.1.0/mini-graph-card-bundle.js",
      "visit_repo": "https://github.com/kalkih/mini-graph-card",
      "changelog": "https://github.com/kalkih/mini-graph-card/releases/latest"
    }
}

```

**Comment by AcidSleeper** [comment]
You have to make a tracker.json file at your repo aswell! 

I belive that is all anyway... =/

**Comment by iammexx** [comment]
This is done.  There is a version.json file that you can use.
