### ISSUE TITLE
Keep getting 0:0:0 Uncaught

### ISSUE THREAD

**Issue by IIIdefconIII** [iammexx/home-assistant-config#3]
Whenever i add the card in v 0.84 im getting this error
`Keep getting 0:0:0 Uncaught`

```
  - type: module
    url: /local/custom_ui/dark-sky-weather-card.js?v10
```

**Comment by DavidFW1960** [comment]
I think your ?v10 is wrong.
```
  - url: /local/custom_ui/dark-sky-weather-card.js?v=7.1
    type: module
```

**Comment by IIIdefconIII** [comment]
changed that, now getting
`https://unpkg.com/@polymer/polymer@3.1.0/lib/utils/async.js?module:44:11 Uncaught TypeError: Cannot read property 'state' of undefined
`
