### ISSUE TITLE
Custom element doesn't exist: dark-sky-weather-card when accessing through NGINX proxy

### ISSUE THREAD

**Issue by jayscovill** [iammexx/home-assistant-config#36]
Anyone else experiencing the custom card erroring out when accessing homeassistant (hassio .98.4) through an nginx proxy and duckdns.org?

Works fine as soon as I VPN in and use the local host name for my hassio install.

**Comment by HorizonKane** [comment]
I experience the same through Home Assistant cloud service, however I don't know if it would work from home.

If so it might have something to do with the base_url setting? Will check later when at home.

**Comment by jayscovill** [comment]
This has been resolved for me.  Turned out I had an auth_basic_user_file statement in my NGINX proxy conf for the /local URL that was causing that custom card to fail.  It wasn't affecting any other pages or  cards for some reason until today which made me go back and check the logs.  It was failing to authenticate for any custom cards.

Once I removed the authentication statement the card started displaying properly.
