### ISSUE TITLE
Conflict with Button Entity Row card

### ISSUE THREAD

**Issue by SeLLeRoNe** [iammexx/home-assistant-config#37]
Hi there,
I am not really sure someone is gonna pick this up, considering the amount of open issue I don't feel like this card is being mantained anymore.

I think I found a conflict with the Button Entity Card, I did open an Issue on their github repository but it looks more something related to the DarkSky Weather Card, therefore... here I am :)
(Issue opened there: https://github.com/custom-cards/button-entity-row/issues/9)

Long story short, the darksky-weather-card stop working with this error:
Uncaught SyntaxError: Identifier 'LitElement' has already been declared
at dark-sky-weather-card.js:1

This is happening only when i load (not use, simply load the resource in the configuration) the button-entity-row card

I am not a developer so I am not really capable of debug it more myself, but I am available if you need further informations (if that is something you need fix on your end).

Thanks
Andrea

**Comment by jazzyisj** [comment]
@SeLLeRoNe 

It must be something specific with your setup.  I use both this card and the button-entity-row without any issues.  But I think you're correct about this card not being maintained.  Unfortunately, it's been, months since the last update.

**Comment by SeLLeRoNe** [comment]
Hi @jazzyisj ,
Thanks for you reply, actually the problem has been identified in "it was me" :D

Apparently I was using the DarkSky Weather Card loaded as js rather than module.. for some odd reason...

Changing it to "module" fixed the problem ;)
