### ISSUE TITLE
Custom element doesn't exist: dark-sky-weather-card

### ISSUE THREAD

**Issue by chelming** [iammexx/home-assistant-config#5]
This just started happening to me without me changing anything. It appears that there are issues with the CDN Lit uses (see: https://github.com/kalkih/mini-media-player/pull/58/files).

I tried replacing the import with the 4 lines from that PR but it didn't fix it for me, I end up with an empty card.

**Comment by wklink** [comment]
I'm having the same issue.  I replaced the first line with:

```
import { LitElement, html, } from 'https://unpkg-gcp.firebaseapp.com/@polymer/lit-element@0.5.2/lit-element.js?module';
```

and it seems to be working.

**Comment by wklink** [comment]
It looks like the original URL, https://unpkg.com/@polymer/lit-element@^0.5.2/lit-element.js?module, is trying to import it's dependecies from localhost instead of unpkg.com.

**Comment by ohminy** [comment]
wklink!
I was stuck in the same issue suddenly since few hours ago!
but your comment is working for me. 
thanks a lot!

solution
1. change the first line dark-sky-weather-card.js file as follow wklink comment
2. delet all the cookies in my browser (chrome)
3. reboot HA

**Comment by DavidFW1960** [comment]
fixed it for me as well

**Comment by iammexx** [comment]
@wklink 

Thanks for the reference update.  The original line was based on the code samples in the original Lovelace docs.  It's worked fine until now.

**Comment by CMaxim77** [comment]
Fixed it for me too, THANK YOU!!!
